import localFont from "next/font/local";
import "./globals.css";

{
  /*const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
}

const gordon = localFont({
  src: "./fonts/CSGordon.otf",
  variable: "--font-c-s-gordon",
  weight: "100 900",
});*/
}

const csGordon = localFont({
  src: "./fonts/CSGordonRegular.ttf",
  variable: "--font-c-s-gordon",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${csGordon.variable} antialiased`}>{children}</body>
    </html>
  );
}
