const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAIL = 'REGISTER_FAIL';
const SET_ALERT = 'SET_ALERT';
const REMOVE_ALERT = 'REMOVE_ALERT';

export { REGISTER_SUCCESS, REGISTER_FAIL, SET_ALERT, REMOVE_ALERT };
